<?php

const CONFIG_NUMBER_ENTRIES = 100000;
const CONFIG_DATA_PATH = "/tmp/data";

$GLOBALS['CONFIG_MYSQL_HOST'] = $_ENV['MYSQL_HOST'];
$GLOBALS['CONFIG_MYSQL_PORT'] = $_ENV['MYSQL_PORT'];
$GLOBALS['CONFIG_MYSQL_USER'] = $_ENV['MYSQL_USER'];
$GLOBALS['CONFIG_MYSQL_PASSWORD'] = $_ENV['MYSQL_PASSWORD'];