services:
  web:
    image: "no_dbms_use_files/node/web"
    build:
      context: web
    ports:
      - "8081:80"
    volumes:
      - ./web/src:/app
      - /app/node_modules
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootdbpassword
    restart: unless-stopped
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=rootdbpassword
    ports:
      - "3306:3306"
      - "3306:3306"